### ISSUE TITLE
Crash instead of error recovery.

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/sqlite-object-cache#25]
Steven Sullivan (@ss88_uk on w.org) reports this traceback.

Stack trace:
2023/02/17 19:45:34 [error] 20347#20347: *586511 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function lastErrorMsg() on null
 in /home/XXX/webapps/XXX/wp-content/object-cache.php:450
#10 [" while reading response header from upstream, client: 141.101.98.123, server: XXX.org, request: "GET /wp-admin/options-general.php?page=sqlite_object_cache_settings HTTP/2.0", upstream: "fastcgi://unix:/var/run/XXX.sock:", host: "www.XXX.org", referrer: "https://www.XXX.org/wp-admin/plugins.php"
#9 /home/XXX/webapps/XXX/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain()
#8 /home/XXX/webapps/XXX/wp-includes/l10n.php(866): determine_locale()
#7 /home/XXX/webapps/XXX/wp-includes/l10n.php(139): get_locale()
#6 /home/XXX/webapps/XXX/wp-includes/l10n.php(63): get_option()
#5 /home/XXX/webapps/XXX/wp-includes/option.php(165): wp_cache_get()
#4 /home/XXX/webapps/XXX/wp-content/object-cache.php(2172): WP_Object_Cache->get()
#3 /home/XXX/webapps/XXX/wp-content/object-cache.php(1555): WP_Object_Cache->cache_item_exists()
#2 /home/XXX/webapps/XXX/wp-content/object-cache.php(1233): WP_Object_Cache->getone()
#1 /home/XXX/webapps/XXX/wp-content/object-cache.php(1267): WP_Object_Cache->open_connection()

**Comment by OllieJones** [comment]
Fixed in 1.2.2
